INSERT INTO diagnosticos (descripcion)
VALUES
('Hipertensión arterial'),
('Diabetes tipo 2'),
('Cáncer de pulmón'),
('Enfermedad pulmonar obstructiva crónica'),
('Artritis reumatoide'),
('Infarto de miocardio'),
('Accidente cerebrovascular'),
('Insuficiencia renal crónica'),
('Asma bronquial'),
('Apnea del sueño'),
('Obesidad mórbida'),
('Trastorno depresivo mayor'),
('Anemia ferropénica'),
('Gripe estacional'),
('Cáncer de colon'),
('Cálculos renales'),
('Lumbalgia crónica'),
('Hipotiroidismo'),
('Esquizofrenia'),
('Trastorno de ansiedad generalizada'),
('Infección urinaria recurrente'),
('Eczema atópico'),
('Fiebre tifoidea'),
('Malaria'),
('Hepatitis B crónica'),
('Gastritis crónica'),
('Tuberculosis pulmonar'),
('Parkinson'),
('Migraña'),
('Síndrome de fatiga crónica'),
('Cáncer de mama'),
('Cálculos biliares'),
('Síndrome de Down'),
('Tensión arterial elevada'),
('Trastorno obsesivo-compulsivo'),
('Artritis psoriásica'),
('Neumonía bacteriana'),
('Hernia discal'),
('Trastorno bipolar'),
('Enfermedad de Alzheimer'),
('Cefalea tensional'),
('Endometriosis'),
('Cáncer de próstata'),
('Cistitis intersticial'),
('Esclerosis múltiple'),
('Arteriosclerosis'),
('Enfermedad de Crohn'),
('Faringitis estreptocócica'),
('Síndrome del túnel carpiano'),
('Colitis ulcerosa'),
('Linfoma'),
('Fibromialgia'),
('Hipoglucemia',
'Piedras en los riñones'),
('SÍndrome del ovario poliquístico'),
('Trastorno de la conducta alimentaria'),
('Anorexia nerviosa'),
('Bulimia nerviosa'),
('Reflujo gastroesofágico'),
('Insuficiencia hepática'),
('Espondilitis anquilosante'),
('Enfermedad celíaca'),
('Malformación de Chiari'),
('Pneumonía viral'),
('Úlcera gástrica'),
('Trombosis venosa profunda'),
('Arritmias cardíacas'),
('Hepatitis C'),
('Enfermedad de Paget'),
('Malformación arteriovenosa'),
('Fiebre reumática'),
('Leucemia'),
('Meningitis'),
('Bipolaridad'),
('Cáncer de riñón'),
('Sindrome de Guillain-Barré'),
('Cáncer de esófago'),
('Cáncer de hígado'),
('Candidiasis'),
('Apendicitis'),
('Sarcoidosis'),
('Sinusitis crónica'),
('Síndrome de Marfan'),
('Alopecia areata'),
('Psoriasis en placas'),
('Vasculitis autoinmunitaria'),
('Hidrocefalia'),
('Mielitis transversa'),
('Parálisis facial'),
('Trombocitopatía'),
('Dermatitis seborreica'),
('Hipercalcemia'),
('Trastorno límite de la personalidad');

INSERT INTO especialidad (descripcion)
VALUES
('Clinica'),
('Cardiología'),
('Neurología'),
('Oncología'),
('Ginecología'),
('Pediatría'),
('Ortopedia'),
('Dermatología'),
('Psiquiatría'),
('Medicina interna'),
('Radiología');

INSERT INTO vademecum (nombre_comercial, principio_activo)
VALUES
('Paracetamol', 'Paracetamol'),
('Ibuprofeno', 'Ibuprofeno'),
('Amoxicilina', 'Amoxicilina'),
('Aspirina', 'Ácido acetilsalicílico'),
('Losartán', 'Losartán'),
('Loratadina', 'Loratadina'),
('Metformina', 'Metformina'),
('Omeprazol', 'Omeprazol'),
('Atorvastatina', 'Atorvastatina'),
('Fluoxetina', 'Fluoxetina'),
('Ciprofloxacino', 'Ciprofloxacino'),
('Clonazepam', 'Clonazepam'),
('Alprazolam', 'Alprazolam'),
('Salbutamol', 'Salbutamol'),
('Enalapril', 'Enalapril'),
('Naproxeno', 'Naproxeno'),
('Dexametasona', 'Dexametasona'),
('Ketorolaco', 'Ketorolaco'),
('Lisinopril', 'Lisinopril'),
('Furosemida', 'Furosemida'),
('Ranitidina', 'Ranitidina'),
('Doxiciclina', 'Doxiciclina'),
('Tamsulosina', 'Tamsulosina'),
('Prednisona', 'Prednisona'),
('Amoxiclav', 'Amoxicilina + Ácido clavulánico'),
('Gabapentina', 'Gabapentina'),
('Mirtazapina', 'Mirtazapina'),
('Pantoprazol', 'Pantoprazol'),
('Cefalexina', 'Cefalexina'),
('Carvedilol', 'Carvedilol'),
('Loratadina', 'Loratadina'),
('Clorhidrato de metformina', 'Metformina'),
('Valsartán', 'Valsartán'),
('Clorazepato', 'Clorazepato'),
('Fexofenadina', 'Fexofenadina'),
('Sulfato de magnesio', 'Sulfato de magnesio'),
('Bromazepam', 'Bromazepam'),
('Propranolol', 'Propranolol'),
('Cefuroxima', 'Cefuroxima'),
('Tramadol', 'Tramadol'),
('Levotiroxina', 'Levotiroxina'),
('Sertralina', 'Sertralina'),
('Fluconazol', 'Fluconazol'),
('Mometasona', 'Mometasona'),
('Valproato', 'Valproato sódico'),
('Triciclico', 'Amitriptilina'),
('Metronidazol', 'Metronidazol'),
('Mebendazol', 'Mebendazol'),
('Sildenafil', 'Sildenafil'),
('Citalopram', 'Citalopram'),
('Bupropión', 'Bupropión'),
('Espironolactona', 'Espironolactona'),
('Clindamicina', 'Clindamicina'),
('Fosfomicina', 'Fosfomicina'),
('Ceftriaxona', 'Ceftriaxona'),
('Fentanilo', 'Fentanilo'),
('Lorazepam', 'Lorazepam'),
('Azitromicina', 'Azitromicina'),
('Enalapril', 'Enalapril'),
('Baclofeno', 'Baclofeno'),
('Ciprofloxacino', 'Ciprofloxacino'),
('Duloxetina', 'Duloxetina'),
('Salmeterol', 'Salmeterol'),
('Fluorocinolona', 'Fluorocinolona'),
('Mefenámico', 'Ácido mefenámico'),
('Hydroxyzine', 'Hydroxyzine'),
('Amlodipino', 'Amlodipino'),
('Levamisol', 'Levamisol'),
('Sumatriptán', 'Sumatriptán'),
('Zopiclona', 'Zopiclona'),
('Hydrochlorothiazide', 'Hidroclorotiazida'),
('Verapamilo', 'Verapamilo'),
('Oxazepam', 'Oxazepam'),
('Mirtazapina', 'Mirtazapina'),
('Ciprofloxacino', 'Ciprofloxacino'),
('Rifampicina', 'Rifampicina'),
('Digoxina', 'Digoxina'),
('Nitroglicerina', 'Nitroglicerina'),
('Metilprednisolona', 'Metilprednisolona'),
('Escitalopram', 'Escitalopram'),
('Difenhidramina', 'Difenhidramina'),
('Lansoprazol', 'Lansoprazol'),
('Propranolol', 'Propranolol'),
('Clozapina', 'Clozapina'),
('Buspirona', 'Buspirona'),
('Fentermina', 'Fentermina'),
('Topiramato', 'Topiramato'),
('Colchicina', 'Colchicina'),
('Tamsulosina', 'Tamsulosina'),
('Naltrexona', 'Naltrexona'),
('Bupropión', 'Bupropión'),
('Ciprofloxacino', 'Ciprofloxacino'),
('Isotretinoína', 'Isotretinoína'),
('Zolpidem', 'Zolpidem'),
('Ketoprofeno', 'Ketoprofeno'),
('Benzocaína', 'Benzocaína'),
('Montelukast', 'Montelukast'),
('Tizanidina', 'Tizanidina'),
('Clorhidrato de clorfeniramina', 'Clorfeniramina'),
('Clonidina', 'Clonidina'),
('Etoricoxib', 'Etoricoxib'),
('Atenolol', 'Atenolol'),
('Ranitidina', 'Ranitidina'),
('Captopril', 'Captopril'),
('Sulfato de hierro', 'Sulfato de hierro'),
('Sildenafil', 'Sildenafil'),
('Cefadroxilo', 'Cefadroxilo'),
('Loratadina', 'Loratadina'),
('Carbamazepina', 'Carbamazepina'),
('Fenobarbital', 'Fenobarbital'),
('Tramadol', 'Tramadol'),
('Piroxicam', 'Piroxicam'),
('Folicil', 'Ácido fólico'),
('Tetrahidrocannabinol', 'Tetrahidrocannabinol'),
('Clonazepam', 'Clonazepam'),
('Moxifloxacino', 'Moxifloxacino');

INSERT INTO medico (id_medico, nombre, apellido, telefono, email, id_especialidad)
VALUES
(1234, 'Juan', 'Pérez', 5551234567, 'juan.perez@email.com', 1),
(5678, 'Ana', 'Gómez', 5552345678, 'ana.gomez@email.com', 2),
(2345, 'Carlos', 'López', 5553456789, 'carlos.lopez@email.com', 3),
(6789, 'María', 'Fernández', 5554567890, 'maria.fernandez@email.com', 4),
(3456, 'Luis', 'Martínez', 5555678901, 'luis.martinez@email.com', 5),
(7890, 'Laura', 'Sánchez', 5556789012, 'laura.sanchez@email.com', 6),
(4321, 'Pedro', 'Ramírez', 5557890123, 'pedro.ramirez@email.com', 7),
(8765, 'Elena', 'Rodríguez', 5558901234, 'elena.rodriguez@email.com', 8),
(5674, 'José', 'García', 5559012345, 'jose.garcia@email.com', 9),
(4320, 'Patricia', 'Vega', 5550123456, 'patricia.vega@email.com', 10),
(2341, 'Miguel', 'Hernández', 5551239876, 'miguel.hernandez@email.com', 1),
(6783, 'Carmen', 'Jiménez', 5552348765, 'carmen.jimenez@email.com', 2),
(3457, 'Antonio', 'Blanco', 5553457654, 'antonio.blanco@email.com', 3),
(7891, 'Sofía', 'Mendoza', 5554566543, 'sofia.mendoza@email.com', 4),
(4322, 'Raúl', 'Suárez', 5555675432, 'raul.suarez@email.com', 5),
(8766, 'Marta', 'Castro', 5556784321, 'marta.castro@email.com', 6),
(5675, 'David', 'Ruiz', 5557893210, 'david.ruiz@email.com', 7),
(4323, 'Isabel', 'Torres', 5558902109, 'isabel.torres@email.com', 8),
(2342, 'Javier', 'Giménez', 5559011098, 'javier.gimenez@email.com', 9),
(6784, 'Beatriz', 'Córdoba', 5550120987, 'beatriz.cordoba@email.com', 10);